GET http://localhost:8080/allFlights

###
GET http://localhost:8080/flight?departureDate=2023-12-10&returnDate=2023-12-16&destination=Frankfurt

###
GET http://localhost:8080/flight?departureDate=2023-12-10&returnDate=2023-12-16&destination=Taipei

###
GET http://localhost:8080/flight?departureDate=2023-12-10&returnDate=2023-12-16&destination=a

###
GET http://localhost:8080/allHotels

###
GET http://localhost:8080/hotel?checkInDate=2023-12-10&checkOutDate=2023-12-16&destination=Frankfurt

###
GET http://localhost:8080/